id: AC94B64A5
base_file: f0D76.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:24:57.291191
  last_modified_at: 2022-06-17 12:24:57.291199
