id: AC94B64A5
base_file: fBA8A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:24:57.295787
  last_modified_at: 2022-06-17 12:24:57.295790
